#+title: FAIM Resources
#+author: Gerard Bentley
#+date: <2020-01-22 Wed>

Collection of resources for new and current FAIM lab members.

For easiest viewing, you can open the index.html file in the 'public' directory

You can download the folder via gitlab or with the following terminal commands

#+BEGIN_SRC bash
  git clone https://pom-itb-gitlab01.campus.pomona.edu/faim-lab/faim-resources.git faim_resources
  cd faim_resources/public
  open index.html
#+END_SRC

* Org-mode
Org-mode is [[http://www.gnu.org/philosophy/free-sw.en.html][Free Software]] and part of [[https://www.gnu.org/s/emacs/][GNU Emacs]].  It's a simple
document format ("Org") with a powerful and intuitive interface
(org-mode) that can [[http://orgmode.org/org.html#Exporting][export]] and [[http://orgmode.org/org.html#Publishing][publish]] to html, LaTeX, ascii, odt
amongst others, and [[http://orgmode.org/org.html#Working-with-source-code][evaluate source code]].

The org-mode manual can be accessed here: [[http://orgmode.org/org.html]].

The main place for Org development is the mailing list, available on
[[http://dir.gmane.org/gmane.emacs.orgmode][Gmane]].

* Gitlab CI

This project's static Pages are built by [[https://about.gitlab.com/gitlab-ci/][GitLab CI]] according to file =.gitlab-ci.yml=:

#+INCLUDE: ".gitlab-ci.yml" src conf

These build instructions are using a docker image, namely ~iquiw/alpine-emacs~.
It makes it possible to publish the project on a public runner on
Gitlab.com.

You could probably get a better experience by using a local runner on
a server you control.  If so, you can drop the ~image~ keyword.


* GitLab User or Group Pages

To use this project as your user/group website, you will need one
additional step: just rename your project to ~namespace.gitlab.io~,
where ~namespace~ is your ~username~ or ~groupname~. This can be done by
navigating to your project's Settings.

Read more about [[https://docs.gitlab.com/ce/user/project/pages/#user-or-group-pages][user/group Pages]] and [[https://docs.gitlab.com/ce/user/project/pages/#project-pages][project Pages]].

---

Forked from [[https://gitlab.com/pank/org-mode-gitlab-pages]] via [[https://gitlab.com/pages/org-mode]]
